In [1]:
import numpy as np

In [4]:
def initialize_matrix(nh):

    matrix = [[1, 0, -1] for _ in range(0, nh)]
    return matrix

In [17]:
def forward_prop(A_iput, matrix):
    AL[n] = np.sum(np.matmul(A_iput, matrix))
    AL = 

    return AL

In [109]:
A_input = [[30, 30, 0, 10] for _ in range(0,  4)]
A_input

[[30, 30, 0, 10], [30, 30, 0, 10], [30, 30, 0, 10], [30, 30, 0, 10]]

In [120]:
A_input = [[30, 20, 0, 30], [34, 43, 0, 20], [32, 33, 0, 21], [234, 32, 0, 40]]

In [121]:
A = np.matrix(A_input)

matrix_filter = initialize_matrix(3)
filter = np.matrix(matrix_filter)

filter

matrix([[ 1,  0, -1],
        [ 1,  0, -1],
        [ 1,  0, -1]])

In [142]:
A_[0][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [137]:
A_ = A[:filter.shape[1]]
for row in A_:
    print (row)

[[30 20  0 30]]
[[34 43  0 20]]
[[32 33  0 21]]


In [28]:
forward_prop(A, filter)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
def convulational_layer(A_input, nh, nw, np):
    
    np.matrix(nh, nw)

    np.w
    
    for c in A_input:
        c 


